panel de administracion vista
dcarolinahdev/stack_commerce_front pull request #5
Opened 2023-08-31 15:32 UTC by harold12a

modified:   src/App.jsx
	new file:   src/pages/Admin.jsx
	modified:   src/pages/router.jsx

2023-08-31 15:38 UTC, dcarolinahdev approved these changes

2023-08-31 16:00 UTC, SantiagoGutierrez896 approved these changes

2023-08-31 16:15 UTC, GuillermoDuKe requested changes
Revisa las rutas

2023-09-01 01:28 UTC, ROBERTG96 approved these changes

2023-09-01 16:11 UTC, GuillermoDuKe approved these changes

2023-09-01 16:11 UTC, merged